### ISSUE TITLE
The LIMIT clause is not used in SQL Server.

### ISSUE THREAD

**Issue by aymiee** [NikhilSehgal123/Azure-OpenAI-SQL#1]
This is great but I did notice that the example is for SQLLite, and I am using SQL Server.  The LIMIT clause is not used in SQL Server.  ChatGPT is generating SQL queries with "LIMIT 1" in response to prompts.  Probably because it is leveraging its training to construct SQL queries based on typical SQL syntax, which often includes clauses like "LIMIT 1" to limit the results to a single record.

I had to explicit state:
SYSTEM_MESSAGE = """You are an AI assistant that is able to convert natural language into a properly formatted SQL query for SQL Server.  The "LIMIT" Clause is not used.

**Comment by NikhilSehgal123** [comment]
Hey @aymiee, this is now solved in the main repo, thanks!
