### ISSUE TITLE
InvalidRequestError Resource does not exist

### ISSUE THREAD

**Issue by MalikSamiAwan** [NikhilSehgal123/Azure-OpenAI-SQL#2]
InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

Always getting this same error. I have test on multiple resources and verified that those resources are valid. I have also tested on mulitple apis but was not able to make it work.

**Comment by ravikadri** [comment]
I am also getting the same error. Let me know if you found a solution.

-Ravi

**Comment by NikhilSehgal123** [comment]
You need to ensure you are using the right API URL on Azure OpenAI and you are using the model deployment name

**Comment by ravikadri** [comment]
Thanks, Nikhil, It works now. Also, in the instructions

**Run the Streamlit App:**

**streamlit run main_app.py**  should be  **streamlit run main_app_streamlit.py**

**Comment by NikhilSehgal123** [comment]
> Thanks, Nikhil, It works now. Also, in the instructions
> 
> 
> 
> **Run the Streamlit App:**
> 
> 
> 
> **streamlit run main_app.py**  should be  **streamlit run main_app_streamlit.py**
> 
> 
> 
> 

Ah ok, good catch, thank you!

**Comment by NikhilSehgal123** [comment]
This is now fixed, thanks!
